# Generated by Django 3.1.5 on 2021-02-02 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('test', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('friendly_id', models.IntegerField(blank=True, null=True)),
                ('to_customer', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, max_length=128, null=True)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('address_2', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('zip', models.CharField(blank=True, max_length=128, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('subtotal_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('shipping_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('stripe_token', models.CharField(blank=True, max_length=128, null=True)),
                ('paypal_trans', models.CharField(blank=True, max_length=128, null=True)),
                ('patch_path', models.CharField(blank=True, max_length=128, null=True)),
                ('has_payment_error', models.BooleanField(default=False)),
                ('easyship_address_id', models.CharField(blank=True, max_length=256, null=True)),
                ('easyship_address_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='design/finished')),
                ('rotation', models.IntegerField(blank=True, default=0)),
                ('dimension_x', models.IntegerField(blank=True, null=True)),
                ('dimension_y', models.IntegerField(blank=True, null=True)),
                ('pre_made', models.BooleanField(default=False, help_text='Is FM Expressions in Stock?')),
            ],
        ),
        migrations.CreateModel(
            name='Printable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(default='Shirt', max_length=128)),
                ('title', models.CharField(help_text='What does the customer see?', max_length=128)),
                ('print_label_name', models.CharField(blank=True, help_text='e.x. Bella Canvas 3001', max_length=128, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='printable/icon')),
                ('base_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('details', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('sizing', markdownx.models.MarkdownxField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrintableMockup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='printable/mockup')),
                ('name', models.CharField(max_length=128)),
                ('design_x0', models.IntegerField(blank=True, default=0, null=True)),
                ('design_y0', models.IntegerField(blank=True, default=0, null=True)),
                ('design_x1', models.IntegerField(blank=True, default=0, null=True)),
                ('design_y1', models.IntegerField(blank=True, default=0, null=True)),
                ('rotate', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('activated_on', models.DateTimeField()),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('address_2', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('zip', models.CharField(blank=True, max_length=128, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StorePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=True)),
                ('stripe_token', models.CharField(max_length=128)),
                ('last_4', models.CharField(max_length=4)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.store')),
            ],
        ),
        migrations.CreateModel(
            name='PrintableOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=128, null=True)),
                ('size_display', models.CharField(blank=True, max_length=128, null=True)),
                ('color', models.CharField(blank=True, max_length=128, null=True)),
                ('color_css', models.CharField(blank=True, max_length=128, null=True)),
                ('stock', models.IntegerField(default=1000)),
                ('extra_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('additional_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('mockup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.printablemockup')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.printable')),
            ],
        ),
        migrations.AddField(
            model_name='printable',
            name='default_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.printablemockup'),
        ),
        migrations.CreateModel(
            name='DesignPrintable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('F', 'Front'), ('B', 'Back')], max_length=1)),
                ('pos_x', models.IntegerField(default=0)),
                ('pos_y', models.IntegerField(default=0)),
                ('pos_h', models.IntegerField(default=6000)),
                ('pos_w', models.IntegerField(default=6000)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.design')),
                ('options', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.printableoption')),
                ('printable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.printable')),
            ],
        ),
        migrations.CreateModel(
            name='CartStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.cart')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.status')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='current_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_status', to='engine.cartstatus'),
        ),
        migrations.AddField(
            model_name='cart',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.store'),
        ),
    ]
